name: "Run integration tests"
description: "Run Inspektor Gadget integration tests"

inputs:
  registry:
    description: 'Server address of registry where integration tests container image will be pushed'
    required: false
  username:
    description: 'Username used to log against the registry'
    required: false
  password:
    description: 'Password or access token used to log against the registry'
    required: false

runs:
  using: "composite"
  steps:
    - name: Set IMAGE_TAG
      shell: bash
      run: |
        TMP1=${GITHUB_REF#*/}
        TMP2=${TMP1#*/}
        IMAGE_TAG=${TMP2//\//-}
        if [ "$IMAGE_TAG" = "main" ]; then
            IMAGE_TAG="latest"
        fi
        echo IMAGE_TAG=$IMAGE_TAG >> $GITHUB_ENV
    - name: Get kubectl-gadget-linux-amd64.tar.gz from artifact.
      uses: actions/download-artifact@v2
      with:
        name: kubectl-gadget-linux-amd64-tar-gz
        path: /home/runner/work/inspektor-gadget/
    - name: Integration tests
      shell: bash
      run: |
        echo "IntegrationTestsJob: Using IMAGE_TAG=$IMAGE_TAG"

        tar zxvf /home/runner/work/inspektor-gadget/kubectl-gadget-linux-amd64.tar.gz
        mv kubectl-gadget kubectl-gadget-linux-amd64

        cleanup() { \
            echo "IntegrationTestsJob: Workflow run is being cancelled: $1 was received"; \
            trap - $1; \
            if [[ $1 == "SIGINT" ]]; then \
              echo "IntegrationTestsJob: Start the clean-up..."; \
            else \
              echo "IntegrationTestsJob: Just wait until the clean-up finishes..."; \
              return; \
            fi; \
            echo "IntegrationTestsJob: Notifying the integration tests container about the cancellation"; \
            docker kill --signal="SIGINT" ig-integration-tests > /dev/null; \
            echo "IntegrationTestsJob: Waiting for the integration tests container to finish"; \
            docker wait ig-integration-tests & wait $!; \
            echo "IntegrationTestsJob: We are done with the clean-up. Let the job exit"; \
            exit 0; \
        }

        # Capture the SIGINT to start the clean-up. Then, capture also the
        # SIGTERM to have those 2.5 extra seconds before the runner kills the
        # process tree:
        # https://docs.github.com/en/actions/managing-workflow-runs/canceling-a-workflow#steps-github-takes-to-cancel-a-workflow-run
        trap 'cleanup SIGINT' SIGINT
        trap 'cleanup SIGTERM' SIGTERM

        echo "IntegrationTestsJob: Start"
        TESTS_DOCKER_ARGS="-e KUBECONFIG=/root/.kube/config -v /home/runner/.kube:/root/.kube -v /home/runner/work/_temp/.minikube:/home/runner/work/_temp/.minikube" \
            make -C integration build test &
        wait $!
        echo "IntegrationTestsJob: Done"

        sed -i "s/latest/$IMAGE_TAG/g" integration/gadget-integration-tests-job.yaml
    - name: Add integration asset as artifact.
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-artifact@master
      with:
        name: integration-asset
        path: /home/runner/work/inspektor-gadget/inspektor-gadget/integration/gadget-integration-tests-job.yaml
    - name: Login to Container Registry
      if: startsWith(github.ref, 'refs/tags/v')
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: Push Integration Test Image
      shell: bash
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        make -C integration push
