#!/usr/bin/env bash

# Generate container tag names
# From https://github.com/weaveworks/scope/blob/master/tools/image-tag

set -o errexit
set -o pipefail

# If there is an explicit image tag set, just return it
if [ -n "$IMAGE_TAG" ]; then
  echo $IMAGE_TAG
  exit 0
fi

# If this is running in Github Actions, use GITHUB_REF to determine the tag to use
if [ -n "$GITHUB_REF" ]; then
  tag=${GITHUB_REF}
  if [ ${tag} == 'refs/heads/main' ]; then
    tag='latest'
  else
    # Remove refs/*/.
    tag=${tag#refs/*/}
    # Replace / by - to avoid docker push crying.
    tag=${tag/\//-}
  fi
  echo $tag
  exit 0
fi

WORKING_SUFFIX=$(if git status --porcelain | grep -qE '^(?:[^?][^ ]|[^ ][^?])\s'; then echo "-WIP"; else echo ""; fi)
BRANCH_PREFIX=$(git rev-parse --abbrev-ref HEAD)

if [ "$BRANCH_PREFIX" = "main" ] ; then
  BRANCH_PREFIX="latest"
fi
echo "${BRANCH_PREFIX//\//-}$WORKING_SUFFIX"
